service: serverless-example

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  memorySize: 128
  iamRoleStatements:
    - Effect: Allow
      Action: SNS:Publish
      Resource:
        - arn:aws:sns:${self:provider.region}:${aws:accountId}:*
    - Effect: Allow
      Action:
        - sns:*
      Resource: "*"
  environment:
    ACCOUNT_ID: ${aws:accountId}
    REGION: ${self:provider.region}

functions:
  api:
    handler: dist/api.httpApi
    events:
      - httpApi:
          path: /api
          method: get
  sub:
    handler: dist/pubsub.handler
    events: ${file(./dist/pubsub.js):getSubscribedEvents}


resources:
  Resources: ${file(./dist/pubsub.js):getResources}
  Outputs: ${file(./dist/pubsub.js):getOutputFile}
