name: CI

on:
  push:
    branches: "*" # Run on all branches
    paths:
      - 'core/**'
      - '.github/workflows/core.yml'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - uses: pnpm/action-setup@v2
          with:
            version: 7
        - uses: actions/setup-node@v3
          with:
            node-version: 16
            cache: 'pnpm'
        - run: cd core && pnpm install --frozen-lockfile
        - run: cd core && pnpm run lint
