name: Publish

on:
  push:
    branches: [main]
    paths:
      - 'core/**'
      - '.github/workflows/core-publish.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - uses: pnpm/action-setup@v2
          with:
            version: 7
        - uses: actions/setup-node@v3
          with:
            node-version: 16
            cache: 'pnpm'
            cache-dependency-path: core
        - name: Install dependencies
          run: pnpm install --frozen-lockfile
          working-directory: core
        - name: Move ./core/.changeset to ./core
          run: mv ./core/.changeset/* ./core
        - name: Create Release Pull Request or Publish on NPM
          id: changesets
          uses: changesets/action@v1
          with:
            working-directory: core
            publish: cd core && pnpm publish --access public --tag latest --no-git-checks --no-git-tag-version --no-git-reset --no-git-required --no-push --no-commit-hooks --no-lockfile --no-shamefully-hoist --no-update-check --no-verify-access --no-verify-store
          env:
            NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
