name: CI

on:
  push:
    branches: "*" # Run on all branches
    paths:
      - 'core/**'
      - '.github/workflows/core.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        working-directory: core
      - uses: pnpm/action-setup@v2
        working-directory: core
        with:
          version: 7
      - uses: actions/setup-node@v3
        working-directory: core
        with:
          node-version: 16
          cache: 'pnpm'
      - name: Install dependencies
        working-directory: core
        run: pnpm install --frozen-lockfile
      - name: Run lint
        working-directory: core
        run: pnpm run lint
